#!/usr/bin/env zsh

# Navigation alias
alias dev='cd ~/dev'
alias dot='cd ~/.dotfiles'
alias conf='cd ~/.config && ll'
alias zshrc='cd ~/.config/zsh && code ~/.config/zsh'
alias doc='open ~/Dropbox/Documents'
alias notes='code ~/dev/github/orue/notes'
alias meetings='code ~/dev/github/mjphealthcare/meeting-notes'
alias hosts='sudo cot /etc/hosts'
alias gitconfig=' git config --global -e'

#Projects
alias cclear='cd ~/dev/github/mjphealthcare/cclear'
alias cclear-api='cd ~/dev/github/mjphealthcare/cclear/services/cclear-api'

# Alias for run last SQLite
alias my-sqlite="echo 'This is just an alias that is using for the homebrew installed sqlite3. Set up the alias' && /opt/homebrew/opt/sqlite/bin/sqlite3"

# Home Local Servers
alias azul="ssh orue@azul" # home server
