#!/bin/sh

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Generate Password
alias pw='openssl rand -base64 16 | colrm 17'


# NPM
alias npmgl="npm ls -g --depth 0"
alias nkiller='rm -rf node_modules/ && npm install'

# Yarn
alias ykiller='rm -rf node_modules/ && yarn install'

# git aliases
alias github="gh repo view --web"

# Markdown files
alias -s md='code -n'

# JSON files
alias -s json=code

# bulk association
alias -s {cs,ts,html}=code

alias gitconfig='cot ~/.gitconfig'

#  Search terminal history
alias hs='history | grep -i'

# Acitvate Python virtual env
alias activate='source venv/bin/activate'

# App lauchers
alias vim='/opt/homebrew/bin/nvim'
alias charm="open -b com.jetbrains.pycharm ."

# Remote Servers
alias ssh='TERM="xterm-256color" ssh'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'

# Directory views
alias ls='eza --icons -F -H --group-directories-first --git -1'
alias lS='eza -1'			             # one column, just names
alias tree='eza --tree --git-ignore --icons'                      # tree
alias l="eza -ghlH --git --icons"
alias ll="eza -aghlH --git --icons --sort=type"

alias cp='cp -iv'                   # Preferred 'cp' implementation
alias mv='mv -iv'                   # Preferred 'mv' implementation
alias mkdir='mkdir -pv'             # Preferred 'mkdir' implementation
alias rm='rm -i'
alias rmrf='rm -rf'
alias f='open -a Finder ./'         # f:            Opens current directory in MacOS Finder


# history
alias h='history'
alias clear_history='echo "" > ~/.zsh_history & exec $SHELL -l'

# easier to read disk
alias df='df -h'     # human-readable sizes

#Homebrew Update
alias brewup='brew update; brew upgrade; brew upgrade --cask; brew autoremove; brew cleanup; brew doctor'
