#!/bin/sh

# Navigation alias
alias dev='cd ~/dev'
alias dot='cd ~/.dotfiles'
alias conf='cd ~/.config'
alias zshrc='code ~/.config/zsh'
alias doc='open ~/Dropbox/Documents'
alias notes='code ~/dev/github/orue/notes'
alias hosts='sudo subl /etc/hosts'
alias gitconfig='subl ~/.gitconfig'

#Projects
alias cclear='cd ~/dev/github/mjphealthcare/cclear'
alias cclear-api='cd ~/dev/github/mjphealthcare/cclear/services/cclear-api'

# Alias for run last SQLite
alias my-sqlite="echo 'This is just an alias that is using for the homebrew installed sqlite3. Set up the alias' && /opt/homebrew/opt/sqlite/bin/sqlite3"

# Git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gcm='git commit -m'
alias gp='git push'
alias gpl='git pull'
alias gb='git branch'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log'
alias gr='git remote -v'
alias gcl='git clone'


# Home Local Servers
alias azul="ssh orue@azul" # home server
